inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - sorbet/**/*.rbi

Style/AccessorGrouping:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/UselessMethodDefinition:
  Exclude:
    - lib/typed/failure.rb
    - lib/typed/success.rb
